version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - zap-net
  
  zap:
    image: ghcr.io/zaproxy/zap-full-scan
    depends_on:
      - app
    command: zap-baseline.py -t http://app:5000 -r zap-report.html
    networks:
      - zap-net

networks:
  zap-net:
