name: DSO Pipeline

on: [push, pull_request]

jobs:
  sast:
    name: Semgrep - Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
  secrets:
    name: Gitleaks - Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
  containers:
    name: Trivy - Container Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t dso-vulnhunter:latest .
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dso-vulnhunter:latest
          format: table
  iac:
    name: Checkov - IAC Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: bridgecrewio/checkov-action@master
  zap:
    name: OWASP ZAP - DAST Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up --build -d
          sleep 20

      - name: Running DAST Scan
        run: |
          docker-compose run zap
          docker cp $(docker ps -aqf "name=zap"):/zap/zap-report.html ./zap-report.html

      - name: Upload Zap Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: ./zap-report.html